### ISSUE TITLE
crash after TxSearch destroyed

### ISSUE THREAD

**Issue by moneroexamples** [moneroexamples/openmonero#8]
```
Thread 3 "openmonero" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffe7bee3700 (LWP 28256)]
0x0000000000a9e13e in xmreg::TxSearch::still_searching() ()
(gdb) where
#0  0x0000000000a9e13e in xmreg::TxSearch::still_searching() ()
#1  0x0000000000a59d46 in xmreg::CurrentBlockchainStatus::clean_search_thread_map() ()
#2  0x0000000000a5757e in xmreg::CurrentBlockchainStatus::start_monitor_blockchain_thread()::{lambda()#1}::operator()() const ()
#3  0x0000000000a5bbe4 in void std::_Bind_simple<xmreg::CurrentBlockchainStatus::start_monitor_blockchain_thread()::{lambda()#1} ()>::_M_invoke<>(std::_Index_tuple<>) ()
#4  0x0000000000a5bb3a in std::_Bind_simple<xmreg::CurrentBlockchainStatus::start_monitor_blockchain_thread()::{lambda()#1} ()>::operator()() ()
#5  0x0000000000a5baca in std::thread::_Impl<std::_Bind_simple<xmreg::CurrentBlockchainStatus::start_monitor_blockchain_thread()::{lambda()#1} ()> >::_M_run()
    ()
#6  0x00007ffff572fc80 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#7  0x00007ffff65376ba in start_thread (arg=0x7ffe7bee3700)
    at pthread_create.c:333
#8  0x00007ffff53b482d in clone ()
```

**Comment by moneroexamples** [comment]
```
TxSearch destroyed

Thread 3 "openmonero" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffe7bee3700 (LWP 11134)]
0x00000000008d188a in __gnu_cxx::__atomic_add(int volatile*, int) ()
(gdb) where
#0  0x00000000008d188a in __gnu_cxx::__atomic_add(int volatile*, int) ()
#1  0x00000000008d194a in __gnu_cxx::__atomic_add_dispatch(int*, int) ()
#2  0x00000000008e51b3 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_add_ref_copy() ()
#3  0x00000000008e009f in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::__shared_count(std::__shared_count<(__gnu_cxx::_Lock_policy)2> const&) ()
#4  0x0000000000a5eeab in std::__shared_ptr<xmreg::TxSearch, (__gnu_cxx::_Lock_policy)2>::__shared_ptr(std::__shared_ptr<xmreg::TxSearch, (__gnu_cxx::_Lock_policy)2> const&) ()
#5  0x0000000000a5eed1 in std::shared_ptr<xmreg::TxSearch>::shared_ptr(std::shared_ptr<xmreg::TxSearch> const&) ()
#6  0x0000000000a5ef12 in std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::shared_ptr<xmreg::TxSearch> >::pair(std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocat
or<char> > const, std::shared_ptr<xmreg::TxSearch> > const&) ()
#7  0x0000000000a59d2e in xmreg::CurrentBlockchainStatus::clean_search_thread_map() ()
#8  0x0000000000a5757e in xmreg::CurrentBlockchainStatus::start_monitor_blockchain_thread()::{lambda()#1}::operator()() const ()
#9  0x0000000000a5bbe4 in void std::_Bind_simple<xmreg::CurrentBlockchainStatus::start_monitor_blockchain_thread()::{lambda()#1} ()>::_M_invoke<>(std::_Index_tuple<>) ()
#10 0x0000000000a5bb3a in std::_Bind_simple<xmreg::CurrentBlockchainStatus::start_monitor_blockchain_thread()::{lambda()#1} ()>::operator()() ()
#11 0x0000000000a5baca in std::thread::_Impl<std::_Bind_simple<xmreg::CurrentBlockchainStatus::start_monitor_blockchain_thread()::{lambda()#1} ()> >::_M_run()
    ()
#12 0x00007ffff572fc80 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
```
